# Generated by Django 4.0.4 on 2022-06-23 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyreply',
            unique_together={('replier', 'item')},
        ),
    ]
